### ISSUE TITLE
exchange lib for resolving URN/CompactID

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#12]
# Overview
- [MIRIAM](http://www.ebi.ac.uk/miriamws/main/MiriamWebServices) is dead
- https://identifiers.org/ has a new version

# ToDo
- [x] talk to the developers
- [ ] get [cloud-libapi](https://github.com/identifiers-org/cloud-libapi) working
- [ ] upgrade MaSyMoS to use new library/server/dataflow
