### ISSUE TITLE
run docker jar-builder and server-integration on windows

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#20]
:information_source: this issue is just about running it on windows, not testing the script and docker outcome, for that see #21 

# ToDo
- [x] Problem1: CRLF and bash interpretion @ronhenkel 
- [x] Problem2: git-bash path interpretion and docker path assumptions (`/c/` → `c:/`)
    - [x] replace only, if string is starting with this pattern
- [x] Problem3: git-bash/mingw has problems interpreting `docker run alpine ls /` - it tries to output a host path :/
- [x] Problem4: Blank page of neo4j web interface on localhost:7474

**Comment by BradleyScrim** [comment]
:information_source: Problems with line breaks: Tortoise converts `\n` LF into `\r\n` CRFL; git-bash cannot find command `bash\r` :facepalm: 

How to deal with that?

**Comment by BradleyScrim** [comment]
> information_source Problems with line breaks: Tortoise converts `\n` NL into `\r\n` CRNL; git-bash cannot find command `bash\r` facepalm
> 
> How to deal with that?

@ronhenkel , you fixed that, please write down how and send me, I'll add it to the docs, thx!

**Comment by ronhenkel** [comment]
TortoiseGit:
During installation on a Windows System the software asks how to handle Unix/Windows linebreaks. Default is "checkout windows style" and "check in Unix style". This causes trouble when running shell scripts on windows.

If you want to change the behavior for a specific repository do the following:
1. clone/create the desired repository
1. right click on the directory, TortoiseGit -> Settings
1. in the upcomming window click on Git (left)
1. change "Config Source" to local
1. change "AutoCrLf" to input
1. change "SafeCrLf" to true
1. delete all files in the directory except ".git" (this directory may be hidden)
1. right click on the now empty directory, TortoiseGit -> Revert
1. files are pulled again, containing only Unix linebreaks

**Comment by BradleyScrim** [comment]
> TortoiseGit:
> …

thanks @ronhenkel , i added a [troubleshooting page](https://masymos.readthedocs.io/en/latest/use_troubleshooting.html) for these questions and added docs for the general git behaviour

**Comment by BradleyScrim** [comment]
### Problem2: git-bash path interpretion and docker path assumptions

@ronhenkel , I pushed the changes to the scripts and updated the documentation. Find the current version in branch [windows-compatibility](https://github.com/MaSyMoS/masymos-docker/tree/windows-compatibility) - Let's test it together!
