### ISSUE TITLE
test masymos docker, check documentation

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#21]
- test, if running
- check docs for
    - is everything understandable
    - grammar and typo
    - is everything covered, did i miss something?
- please report…
    - OS+version
    - docker version
    - everything, you want to tell us about masymos-docker
    - in this issue

Thank you! :grinning: 

# ToDo
- [ ] - user target group
    - user knows about models
    - explain docker a bit and link the official documentation
- [ ] check docs: [Minimal Userguide to get startet](https://masymos.readthedocs.io/en/latest/main_setup.html)
- [ ] check docs: [masymos-docker documentation, tweaks](https://masymos.readthedocs.io/en/latest/contrib_docker.html)
- [ ] test: jar-builder on linux
- [ ] test: server-integration on linux
- [ ] test: jar-builder on windows
- [ ] test: server-integration on windows
- [ ] are all use cases covered?

:information_source: @ronhenkel
