### ISSUE TITLE
write down concept for masymos-seek-middleware

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#25]
# ToDo
- [ ] create masymos-seek-related documentation apart from the masymos docs
- [ ] mapping table, acitivity diagram, sequence diagram - to show dataflow, push, pull, hooks, requests,…
- [ ] write down decisions so far
- [ ] write down general concept and requirements

@ronhenkel
