### ISSUE TITLE
Morre - how to deal with getting annotations

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#29]
# Overview
- state: on `create_annotation_index` all models without resolved annotations will be queries for search annotations
- this can be very time intensive
- some models' annotations data may not be available

# ToDo
- [ ] implement a counter + timestamp
- on annotation update request…
    - [ ] check counter (skip model, if `counter >10`)
    - [ ] check timestamp (if older then 1d, increment counter)
    - [ ] set timestamp
