### ISSUE TITLE
log4shell-bug - Update log4j in all Java-MaSyMoS-Parts and update all libraries using log4j2

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#32]
# ToDo
- [x] add warning to the documentation
- [ ] update Log4 in MaSyMoS-core
- [ ] update Log4 in MaSyMoS-morre
- [ ] update Log4 in MaSyMoS-cli
- [ ] update Log4 in all libraries using log4j m(
