### ISSUE TITLE
fix loggers

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#5]
# (hopefully) working solution
```diff
-import org.slf4j.Logger;
-import org.slf4j.LoggerFactory;
+import org.apache.log4j.Logger;

-   final Logger logger = LoggerFactory.getLogger(….class);
+   final Logger logger = Logger.getLogger(….class);
```

# ToDo
- [x] replace lines everywhere in the code in all three projects
    - searched and replaced all occurences - replaced slf4j.Loggerfactory with log4j.Logger
    - checked for `slf4j`
    - checked for `LoggerFactory`
    - done in branch `logger` on https://github.com/BradleyScrim
- [x] check pom.xml for old dependencies
- [x] check, if working

**Comment by BradleyScrim** [comment]
@ronhenkel can you please check out the branch `logger` from all [three masymos projects](https://github.com/BradleyScrim?tab=repositories) and run it?

hopefully the logger will work again

Thanks!

**Comment by BradleyScrim** [comment]
@ronhenkel , can you please try this again with a log level of `INFO` until #9 is solved :/

thank you!

**Comment by BradleyScrim** [comment]
@ronhenkel , please try again, I updated the logger branch in core and cli - should work now without changes

thx!

**Comment by BradleyScrim** [comment]
thanks for testing and replying on jabber

i will merge this to the master
