### ISSUE TITLE
Exception thrown from SBML library

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#9]
# Overview
- calling the `MainExtractor` with `-dbPath C:/Masymos/Database/sbml_noAnno -directory C:/Masymos/Data/sbml/curated -modeltype sbml -noAnno -fileMode` and a sbml-files
- results in an exception
- tested on Win10, java 13 by @ronhenkel 
- as we remember, this was working in the version from Dec 6, 2019

## part of the log
<details>
    <summary>click to show a part of the log</summary>

```
2020-06-02 15:51:10,878 - [DEBUG] main org.sbml.jsbml.ASTNode:deriveUnit(ASTNode.java:2360) ASTNode: ASTNode.deriveUnit - before simplify - units = 
2020-06-02 15:51:10,880 - [DEBUG] main org.sbml.jsbml.ASTNode:deriveUnit(ASTNode.java:2361) ASTNode: ASTNode.deriveUnit - after simplify  - units = 
2020-06-02 15:51:10,883 - [DEBUG] main org.sbml.jsbml.ASTNode:addChild(ASTNode.java:1825) ASTNode:  adding child current node: 
ASTNode [type=TIMES, user object keys = [jsbml.allow.invalid.sbml]]  unit:unitDefinition []

Exception in thread "main" Undefined combination of Level 0 and Version 0 for element unitDefinition.
	at org.sbml.jsbml.AbstractSBase.<init>(AbstractSBase.java:282)
	at org.sbml.jsbml.AbstractNamedSBase.<init>(AbstractNamedSBase.java:80)
	at org.sbml.jsbml.UnitDefinition.<init>(UnitDefinition.java:550)
	at org.sbml.jsbml.util.compilers.ASTNodeValue.getUnits(ASTNodeValue.java:243)
	at org.sbml.jsbml.ASTNode.deriveUnit(ASTNode.java:2356)
	at org.sbml.jsbml.ASTNode.astNodeToTree(ASTNode.java:4601)
	at org.sbml.jsbml.ASTNode.addChild(ASTNode.java:1826)
	at org.sbml.jsbml.xml.parsers.MathMLStaxParser.processStartElement(MathMLStaxParser.java:568)
	at org.sbml.jsbml.xml.stax.SBMLReader.processStartElement(SBMLReader.java:1004)
	at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromXMLEventReader(SBMLReader.java:767)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:554)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:564)
	at org.sbml.jsbml.SBMLReader.readSBMLFromStream(SBMLReader.java:251)
	at de.unirostock.sems.masymos.extractor.SBML.SBMLExtractor.extractFromSBML(SBMLExtractor.java:191)
	at de.unirostock.sems.masymos.extractor.SBML.SBMLExtractor.extractStoreIndexSBML(SBMLExtractor.java:67)
	at de.unirostock.sems.masymos.main.MainExtractor.sbmlFileMode(MainExtractor.java:426)
	at de.unirostock.sems.masymos.main.MainExtractor.main(MainExtractor.java:138)
```

</details>

# Problem
- exceptions are thrown, if the log level is set to DEBUG or lower
- this exceptions are thrown by the lib `jsbml-core-1.4`
- same behavior with current version `1.5`
- there is no check for logger mode in masymos
- in both cases somewhere near the `org.sbml.jsbml.ASTNode.deriveUnit()`
- i cannot image a reason of throwing exceptions only in debug mode
- checked: there is no exception hidden by masymos, i.e. an empty catch-block

# ToDo
- [x] find source of this problem → problem in lib `jsbml-core-1.4`
- [x] what to do now?
    - **set the logger for this lib to INFO** ~~and forget?~~
    - catch and handle the exception?
        - if so, what log level do we want to use for this lib in future? :/
    - something else?
- [x] check version `jsbml` in pom, upgrade to 1.5
- [x] create issue for the developers of the library: **[done](https://github.com/sbmlteam/jsbml/issues/218)**
- [ ] wait for the bugfix in the lib → [should be fixed in version 1.6](https://github.com/sbmlteam/jsbml/issues/218#issuecomment-638747937)

**Comment by BradleyScrim** [comment]
- reproduced bug (another Exception!) on debian-linux, java 11 with current `logger` version from [here](https://github.com/BradleyScrim/)
- NO Exception *shown up* with the version from 2020-03-26

<details>
    <summary>show exception at the end of the log</summary>

```
2020-06-03 21:17:45,210 - [DEBUG] main org.sbml.jsbml.ASTNode:deriveUnit(ASTNode.java:2338) ASTNode: ASTNode.deriveUnit - before simplify - units = 
2020-06-03 21:17:45,210 - [DEBUG] main org.sbml.jsbml.ASTNode:deriveUnit(ASTNode.java:2339) ASTNode: ASTNode.deriveUnit - after simplify  - units = 
2020-06-03 21:17:45,210 - [DEBUG] main org.sbml.jsbml.ASTNode:addChild(ASTNode.java:1820) ASTNode:  adding child current node: 
ASTNode [type=TIMES, user object keys = [jsbml.allow.invalid.sbml]]  unit:unitDefinition []

Exception in thread "main" org.sbml.jsbml.SBMLException: Fractions must have one numerator and one denominator, here 0 elements are given.
	at org.sbml.jsbml.ASTNode.compile(ASTNode.java:1966)
	at org.sbml.jsbml.ASTNode.deriveUnit(ASTNode.java:2334)
	at org.sbml.jsbml.ASTNode.astNodeToTree(ASTNode.java:4577)
	at org.sbml.jsbml.ASTNode.addChild(ASTNode.java:1821)
	at org.sbml.jsbml.xml.parsers.MathMLStaxParser.processStartElement(MathMLStaxParser.java:564)
	at org.sbml.jsbml.xml.stax.SBMLReader.processStartElement(SBMLReader.java:981)
	at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromXMLEventReader(SBMLReader.java:744)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:542)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:552)
	at org.sbml.jsbml.SBMLReader.readSBMLFromStream(SBMLReader.java:251)
	at de.unirostock.sems.masymos.extractor.SBML.SBMLExtractor.extractFromSBML(SBMLExtractor.java:191)
	at de.unirostock.sems.masymos.extractor.SBML.SBMLExtractor.extractStoreIndexSBML(SBMLExtractor.java:67)
	at de.unirostock.sems.masymos.main.MainExtractor.sbmlFileMode(MainExtractor.java:426)
	at de.unirostock.sems.masymos.main.MainExtractor.main(MainExtractor.java:138)
```
</details>

**Comment by BradleyScrim** [comment]
i found the trigger: setting the log level to INFO will make the program run smooth 🤨

- log level was on TRACE
- also on DEBUG the exception occurs

so there is some bad code running for debug purpose, yeah

**Comment by BradleyScrim** [comment]
here is the situation; issue description updated

one good thing: this has nothing to do with #5 :D

### Problem
- exceptions are thrown, if the log level is set to DEBUG or lower
- this exceptions are thrown by the lib `jsbml-core-1.4`
- same behavior with current version `1.5`
- there is no check for logger mode in masymos
- in both cases somewhere near the `org.sbml.jsbml.ASTNode.deriveUnit()`
- i cannot image a reason of throwing exceptions only in debug mode
- checked: there is no exception hidden by masymos, i.e. an empty catch-block

### what to do now?
- set the logger for this lib to INFO and forget?
- catch and handle the exception?
	- if so, what log level do we want to use for this lib in future? :/
- something else?

**Comment by ronhenkel** [comment]
Other option: tell the JSBML guys and get this fixed? -> https://github.com/sbmlteam/jsbml 
If no one responds we can direclty contact Andreas or Nicolas

**Comment by BradleyScrim** [comment]
> Other option: tell the JSBML guys and get this fixed? -> https://github.com/sbmlteam/jsbml
> If no one responds we can direclty contact Andreas or Nicolas

yes sure, I'll do that.  
for now I decided to use the option `set the logger for this lib to INFO`

- I updated the logger-branches in core and cli
- our code should run now
- issue description is updated
